trigger:
  branches:
    include:
    - master

jobs:
  - job: Build_And_Publish_Dotnet_Template
    pool:
     vmImage : 'ubuntu-latest'
     variables:
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'

    steps:

    
    # Add template versioning
    
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack template project'
      inputs:
        command: 'pack'
        packagesToPack: '**/KTCU.Dotnet.Templates.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)/nuget-packages'
        #versioningScheme: byEnvVar 
        #versionEnvVar: GitVersion.SemVer 

    #Add dotnet push to NuGet
    #condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master')))
